### ISSUE TITLE
Trims trailing whitespaces even in markdown files

### ISSUE THREAD

**Issue by abinashmeher999** [vivekiitkgp/Dotfiles-vim#5]

**Comment by hargup** [comment]
Can you elaborate on the issue you hare having?

**Comment by vivekiitkgp** [comment]
@abinashmeher999 The current `.vimrc` setup doesn't strip any trailing white spaces by default. You need to manually trigger the `,ss` (i.e., `<leader>ss` ) key binding to have the effect.

You can obviously change the key bindings so that the files are automatically stripped when saved. I however, choose to avoid this because in many projects there are files (including markdown) that contain trailing white spaces. Having automated trimming will add a lot of noise to my `git diff`and difficult to track my changes. Needless to say, reverting everything will not be a trivial task.

I'd rather prefer to make such changes in a separate commit where I can achieve this action by a simple key binding as of now. Not sure if I addressed your query.

**Comment by vivekiitkgp** [comment]
@hargup @abinashmeher999 Additionally, a lot of changes that I make and use are my current active setup is in the branch `my_setup`. Might be more useful.

**Comment by abinashmeher999** [comment]
@vivekiitkgp this happens whenever I save the file using `:w`. It automatically strips the whitespaces. I tried to comment the function, but still no use. I will check your `my_setup` branch and will let you know, if it solved the issue.

**Comment by vivekiitkgp** [comment]
@abinashmeher999 Umm. I cannot understand your statement.

Are you reporting that current setup automatically strips the trailing space or do you want to add a behavior which should do that on `:w`?

**Comment by abinashmeher999** [comment]
@vivekiitkgp The current setup automatically does that. [This](https://gist.github.com/abinashmeher999/e149114eed9458671a84) is what my vimrc looks like.

**Comment by vivekiitkgp** [comment]
I see. Give a shot to the latest HEAD and see if the problem is fixed. The
vimrc show in link is quite old.

**Comment by abinashmeher999** [comment]
Yup, the updated settings work! Thanks a lot @vivekiitkgp! :smiley:

**Comment by vivekiitkgp** [comment]
Cool!

**Comment by abinashmeher999** [comment]
You should add the commands to create symlinks too in the `README.md`. Because that's where I always struggle.
